# Generated by Django 5.1.1 on 2024-10-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0003_alter_citizenprofile_user_alter_officerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='reason',
            field=models.CharField(default='Violation', max_length=50),
        ),
        migrations.AlterField(
            model_name='fine',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
