# Generated by Django 5.1.1 on 2024-10-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0004_fine_reason_alter_fine_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='fine_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Fine',
        ),
    ]
