# Generated by Django 5.1.1 on 2024-10-05 08:03

import django.db.models.deletion
from django.db import migrations, models
import uuid


def set_unique_receipt_ids(apps, schema_editor):
    Transaction = apps.get_model('motorcycle_violation', 'Transaction')
    for transaction in Transaction.objects.all():
        transaction.receipt_id = uuid.uuid4()  # Assign a new unique UUID
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0005_motorcycle_fine_balance_delete_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),  # Add receipt_id field
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('redeem', 'Redeem')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('citizen_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='motorcycle_violation.citizenprofile')),
            ],
        ),
        migrations.RunPython(set_unique_receipt_ids),  # Call the function to set unique receipt IDs
    ]

