# Generated by Django 5.1.1 on 2024-10-05 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0006_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='payable_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='redeemable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='citizen_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycle_violation.citizenprofile'),
        ),
    ]
