# Generated by Django 5.1.1 on 2024-10-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0007_rename_timestamp_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
