# Generated by Django 5.1.1 on 2024-10-05 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0008_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('redeem', 'Redeem')], max_length=10)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('redeemable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receipt_id', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('citizen_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='motorcycle_violation.citizenprofile')),
            ],
        ),
    ]
