# Generated by Django 5.1.1 on 2024-10-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0009_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_fines', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_credits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycle_violation.citizenprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
