# Generated by Django 5.1.1 on 2024-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0010_receipt_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='cropped_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/cropped/'),
        ),
    ]
