# Generated by Django 5.1.1 on 2024-10-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0011_violation_cropped_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='cropped_image',
            field=models.ImageField(blank=True, null=True, upload_to='cropped_images/'),
        ),
    ]
