# Generated by Django 5.1.1 on 2024-10-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0013_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='is_appealed',
            field=models.CharField(choices=[('no', 'No Appeal'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='no', max_length=10),
        ),
    ]
