# Generated by Django 5.1.1 on 2024-10-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0014_violation_is_appealed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violation',
            old_name='is_valid',
            new_name='is_paid',
        ),
    ]
