# Generated by Django 5.1.1 on 2024-10-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0015_rename_is_valid_violation_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='is_appealed',
            field=models.CharField(choices=[('no', 'No Appeal'), ('yes', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='no', max_length=10),
        ),
    ]
