# Generated by Django 5.1.1 on 2024-10-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0016_alter_violation_is_appealed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycle_violation.motorcycle')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_receipts', to='motorcycle_violation.receipt')),
            ],
        ),
    ]
