# Generated by Django 5.1.2 on 2024-10-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0017_motorcyclereceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenprofile',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
