# Generated by Django 5.1.2 on 2025-01-26 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0019_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must be in the format: ABC-1234-12-A', regex='^[A-Z]{3}-\\d{3,4}(-\\d{2})?(-[A-Z])?$')]),
        ),
    ]
