# Generated by Django 5.1.2 on 2025-01-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0020_alter_motorcycle_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
    ]
