# Generated by Django 5.1.2 on 2025-02-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0021_alter_motorcycle_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violation',
            old_name='is_paid',
            new_name='is_downloaded',
        ),
    ]
