# Generated by Django 5.1.2 on 2025-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0022_rename_is_paid_violation_is_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('REDEEMED', 'Redeemed'), ('GENERATED', 'Generated')], default='GENERATED', max_length=10),
        ),
    ]
