# Generated by Django 5.1.2 on 2025-02-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0023_receipt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
