# Generated by Django 5.1.2 on 2025-02-11 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0024_receipt_status_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(auto_now_add=True)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspension_history', to='motorcycle_violation.citizenprofile')),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suspension', to='motorcycle_violation.violation')),
            ],
        ),
    ]
