# Generated by Django 5.1.2 on 2025-02-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0025_suspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspension',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_suspensions', to='motorcycle_violation.officerprofile'),
        ),
    ]
