# Generated by Django 5.1.2 on 2025-02-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0026_suspension_suspended_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspension',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
