# Generated by Django 5.1.2 on 2025-02-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0027_suspension_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspension',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='suspension',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
