# Generated by Django 5.1.2 on 2025-02-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0028_remove_suspension_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspension',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
