# Generated by Django 5.1.2 on 2025-02-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0029_suspension_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspension',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
