# Generated by Django 5.1.2 on 2025-02-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle_violation', '0030_suspension_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='suspension_fines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
