# Generated by Django 5.1.2 on 2025-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motorcycle_violation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="violation",
            name="credit_rewarded",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="violation",
            name="fine_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
